#!/bin/bash
# This script is auto-generated by BGP-SRx Software Suite Software Bundler V1.2
# Date: Wed Feb 15 19:33:34 EST 2017
# CMD: bgp-srx-tools/get-BGPSRx.sh -i nist-srx-bundle-22-4.2.2 4.2.2

echo 'BGP-SRx Software Suite V4.2.2 Build script!'
# Check the parameter $1, if 0 OK if 1 display error $2 and exit

# The prefix directory where everything gets installed in
INSTALL_DIR="$(pwd)/$(dirname $0)"
LOC_PREFIX=$(echo $INSTALL_DIR/local-4.2.2 | sed -e "s/\/\.\//\//g")

DO_CONFIGURE=1
DO_MAKE=1
DO_INSTALL=1

YN=
echo "This script is provided as a helper for building the BGP-SRx Software Suite."
echo "We thoroughly tested this script but still, you use this script at your own risk."
while [ "$YN" == "" ] ; do
  read -p "Do you want to continue? [Y/N] " YN
  case $YN in
    [Yy] ) ;;
    [Nn] ) exit ;;
    *)
      COUNT=$(($COUNT + 1))
      YN="" ;;
  esac
  if [ $COUNT -eq 3 ] ; then
    exit;
  fi
done
YN=
COUNT=

# Check if the configure script exist, if not it generates one.
# If it cannot generate the configure script, it aborts the script with an error
function checkConfig()
{
  if [ ! -e configure ] ; then
    which autoreconf > /dev/null
    if [ ! $? -eq 0 ] ; then
      echo "ERROR: autoconfig is required to build the configuration script - abort!"
      exit 1
    else  
      autoreconf -i --force
    fi
  fi
}

function check()
{
  if [ "$1" -eq 1 ] ; then
    echo "$2"
    cd ..
    exit 1
  fi
}

# This function does the make and make install
# parameter $1 = Product name
function make_install()
{
  local NAME="$1"
  if [ $DO_MAKE -eq 1 ] ; then
    make -j 2
    check $? "Error building $NAME!"
  fi
  if [ $DO_INSTALL -eq 1 ] ; then
    make install
    check $? "Error installing $NAME!"
  fi
  cd ..
}

# Make and install srx-crypto-api-0.2.0.2
DIR=srx-crypto-api-0.2.0.2
NAME=SRxCryptoAPI
echo "Make and install $NAME"...
cd $DIR
if [ $DO_CONFIGURE -eq 1 ] ; then
  # Check if a configure script exist, otherwise try to generate one!
  ./configure --prefix=$LOC_PREFIX CFLAGS="-O0 -g"
  check $? "Error Configuring $NAME!"
fi
make_install $NAME

# Make and install bgpsec-io-0.2.0.6
DIR=bgpsec-io-0.2.0.6
NAME=BGPSEC-IO
echo "Make and install $NAME"...
cd $DIR
if [ $DO_CONFIGURE -eq 1 ] ; then
  # Check if a configure script exist, otherwise try to generate one!
  checkConfig
  ./configure --prefix=$LOC_PREFIX sca_dir=$LOC_PREFIX CFLAGS="-O0 -g"
  check $? "Error Configuring $NAME!"
fi
make_install $NAME

# Make and install srx-server-0.4.0.2
DIR=srx-server-0.4.0.2
NAME=SRx-Server
echo "Make and install $NAME"...
cd $DIR
if [ $DO_CONFIGURE -eq 1 ] ; then
  # Check if a configure script exist, otherwise try to generate one!
  checkConfig
  ./configure --prefix=$LOC_PREFIX sca_dir=$LOC_PREFIX CFLAGS="-O0 -g"
  check $? "Error Configuring $NAME!"
fi
make_install $NAME

# Make and install quagga-srx-0.4.2.3
DIR=quagga-srx-0.4.2.3
NAME=QuaggaSRx
echo "Make and install $NAME"...
cd $DIR
if [ $DO_CONFIGURE -eq 1 ] ; then
  # Check if a configure script exist, otherwise try to generate one!
  checkConfig
  ./configure --prefix=$LOC_PREFIX sca_dir=$LOC_PREFIX srx_dir=$LOC_PREFIX CFLAGS="-O0 -g" --disable-doc --enable-user=root --enable-group=root
  check $? "Error Configuring $NAME!"
fi
make_install $NAME
